on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        
      - name: Setup .NET
        uses: actions/setup-dotnet@3447fd6a9f9e57506b15f895c5b76d3b197dc7c2 # v3.2.0

      - name: Install WASI workload
        run: dotnet workload install wasi-experimental

      - name: Install WASI SDK
        run: |
          curl -L -O https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-20/wasi-sdk_20.0_amd64.deb
          sudo apt install ./wasi-sdk_20.0_amd64.deb
          rm ./wasi-sdk_20.0_amd64.deb
          echo "WASI_SDK_PATH=/opt/wasi-sdk" >> $GITHUB_ENV

      - name: Build
        run: dotnet build

      - name: Publish
        run: dotnet publish --configuration Release -p:WasmPublishPath=$PWD/dist dotnet-wasi-action.csproj